spring:
  cloud:
    gateway:
      routes:
        - id: thirdparty-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates:
#            - Query=url,baidu
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}




#前端项目，/api
